/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.7 and the Filter Design Toolbox 4.4.
 *
 * Generated on: 27-May-2012 19:22:15
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,19 -> [-6.250000e-002 6.250000e-002)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s36,34 -> [-2 2)  (auto determined)
 *   Product         : s31,34 -> [-6.250000e-002 6.250000e-002)  (auto determined)
 *   Accumulator     : s36,34 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2008b\extern\include\tmwtypes.h 
 */
const int filter_len = 64;
const int32_T filter[64] = {
         -3031,       -1472,       -1761,       -2031,       -2263,       -2437,
         -2535,       -2533,       -2412,       -2150,       -1732,       -1143,
          -374,         587,        1731,        3063,        4567,        6227,
          8023,        9927,       11907,       13926,       15944,       17920,
         19813,       21579,       23178,       24575,       25734,       26630,
         27240,       27548,       27548,       27240,       26630,       25734,
         24575,       23178,       21579,       19813,       17920,       15944,
         13926,       11907,        9927,        8023,        6227,        4567,
          3063,        1731,         587,        -374,       -1143,       -1732,
         -2150,       -2412,       -2533,       -2535,       -2437,       -2263,
         -2031,       -1761,       -1472,       -3031
};
